#!/bin/sh

set -e

# Get apache httpd environment variables
. /etc/apache2/envvars

[ -z "${APACHE_RUN_DIR}" ] && { echo "Error: APACHE_RUN_DIR not set"; exit 128; }

# Make run dir
mkdir -p "${APACHE_RUN_DIR}"

# Cleanup stale pids on restart
rm -rf ${APACHE_RUN_DIR}/*

# Run apache httpd in foreground
exec /usr/sbin/apache2 -DFOREGROUND
