#!/bin/sh

set -e

PHP_RUN_PID='/run/php/php8.1-fpm.pid'

# Make run dir
mkdir -p "$(dirname ${PHP_RUN_PID})"

# Cleanup stale pid on restart
rm -f ${PHP_RUN_PID}

# Run php fpm in foreground
exec /usr/sbin/php-fpm8.1 --nodaemonize --fpm-config /etc/php/8.1/fpm/php-fpm.conf
