#!/bin/sh

set -e

PHP_RUN_PID='/run/php/php7.0-fpm.pid'

# Make run dir
mkdir -p "$(dirname ${PHP_RUN_PID})"

# Cleanup stale pid on restart
rm -f ${PHP_RUN_PID}

# Run php fpm in foreground
exec /usr/sbin/php-fpm7.0 --nodaemonize --fpm-config /etc/php/7.0/fpm/php-fpm.conf
