#!/bin/sh

set -e

PHP_RUN_PID='/var/run/php5-fpm.pid'

# Cleanup stale pid on restart
rm -f ${PHP_RUN_PID}

# Run php fpm in foreground
exec /usr/sbin/php5-fpm --nodaemonize --fpm-config /etc/php5/fpm/php-fpm.conf
